-- ECOMMERCE_DW database + the three Medallion schemas (spec Phase 4 layout, verbatim):
--   RAW       <- Bronze mirror   (BRONZE_WEBLOGS / BRONZE_USERS / BRONZE_PRODUCTS)
--   STAGING   <- Silver mirror   (WEBLOGS_CLEAN / USERS_CLEAN / PRODUCTS_CLEAN)
--   ANALYTICS <- Gold            (DIM_USER, DIM_PRODUCT, FACT_USER_ACTIVITY,
--                                 AGG_SESSION_METRICS, ETL_AUDIT_LOG)
-- Run this once, before 02-06.

CREATE DATABASE IF NOT EXISTS ECOMMERCE_DW;

USE DATABASE ECOMMERCE_DW;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
